### ISSUE TITLE
Margin for <li> tag only on right and bottom ...

### ISSUE THREAD

**Issue by napolitano** [tomusborne/lightweight-social-icons#7]
Unfortunately the margin for elements of type <li> was only set for the right and bottom side and protected against overwriting with the `!important` directive.

See:

```css
.lsi-social-icons li {
 padding:0 !important;
 display:inline-block !important;
 *display:inline;
 *zoom:1;
 float:none !important;
 margin:0 8px 8px 0 !important;
 list-style-type:none !important
}

```
This leads to the fact that the icons - despite the corresponding option - cannot be placed in the middle.

**Possible solutions for this:**

- Configurability of the margin via the plugin configuration
- Set a surrounding margin (e.g. 4px for all pages)
- Create three different CSS classes for left, center, right
- ...

For all variants the `!important `directive should be removed to allow overwriting.

Translated with www.DeepL.com/Translator (free version)
